import { getUserId } from "../../../../lib-auth";
import { NextRequest,NextResponse } from "next/server";
import { getDb } from "../../../../db";
import { conversations,messages,notifications } from "../../../../db/schema";
import { eq,or,and,asc } from "drizzle-orm";
export const dynamic="force-dynamic";
async function access(req:NextRequest,id:number){const uid=await getUserId(req);if(!uid)return null;const row=(await getDb().select().from(conversations).where(and(eq(conversations.id,id),or(eq(conversations.buyerId,uid),eq(conversations.sellerId,uid)))).limit(1))[0];return row?{uid,row}:null}
export async function GET(req:NextRequest,{params}:{params:Promise<{id:string}>}){const id=Number((await params).id);if(!Number.isSafeInteger(id))return NextResponse.json({error:"Chat inválido"},{status:400});try{const a=await access(req,id);if(!a)return NextResponse.json({error:"Chat no disponible"},{status:403});const db=getDb();const entries=await db.select().from(messages).where(eq(messages.conversationId,id)).orderBy(asc(messages.id)).limit(200);await db.update(notifications).set({readAt:new Date().toISOString()}).where(and(eq(notifications.recipientId,a.uid),eq(notifications.conversationId,id)));return NextResponse.json({messages:entries,chat:a.row})}catch(e){console.error("chat messages",e);return NextResponse.json({error:"No se pudo abrir el chat"},{status:503})}}
export async function POST(req:NextRequest,{params}:{params:Promise<{id:string}>}){const id=Number((await params).id);if(!Number.isSafeInteger(id))return NextResponse.json({error:"Chat inválido"},{status:400});let body="";try{const b=await req.json() as Record<string,unknown>;body=typeof b.body==="string"?b.body.trim():""}catch{}if(!body||body.length>1000)return NextResponse.json({error:"Escribe un mensaje de hasta 1000 caracteres"},{status:400});try{const a=await access(req,id);if(!a)return NextResponse.json({error:"Chat no disponible"},{status:403});const db=getDb(),now=new Date().toISOString(),recipientId=a.uid===a.row.buyerId?a.row.sellerId:a.row.buyerId;await db.insert(messages).values({conversationId:id,senderId:a.uid,body,createdAt:now});await db.update(conversations).set({updatedAt:now}).where(eq(conversations.id,id));await db.insert(notifications).values({recipientId,type:"mensaje",actorId:a.uid,adId:a.row.adId,conversationId:id,createdAt:now});return NextResponse.json({ok:true},{status:201})}catch(e){console.error("chat send",e);return NextResponse.json({error:"No se pudo enviar"},{status:503})}}
