import { getUserId } from "../../../lib-auth";
import { NextRequest,NextResponse } from "next/server";
import { getDb } from "../../../db";
import { savedSearches } from "../../../db/schema";
import { eq } from "drizzle-orm";
import { categories,cities,cleanText,finiteCoord } from "../../../lib-market";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){const uid=await getUserId(req);if(!uid)return NextResponse.json({searches:[]});try{return NextResponse.json({searches:await getDb().select().from(savedSearches).where(eq(savedSearches.userId,uid)).limit(30)})}catch(e){console.error("saved search get",e);return NextResponse.json({error:"Búsquedas no disponibles"},{status:503})}}
export async function POST(req:NextRequest){const uid=await getUserId(req);if(!uid)return NextResponse.json({error:"Inicia sesión para guardar búsquedas"},{status:401});let b:Record<string,unknown>;try{b=await req.json()}catch{return NextResponse.json({error:"Datos inválidos"},{status:400})}const name=cleanText(b.name,60),query=cleanText(b.query,80),kind=cleanText(b.kind),category=cleanText(b.category),city=cleanText(b.city),condition=cleanText(b.condition),minPrice=b.minPrice===""||b.minPrice==null?null:Number(b.minPrice),maxPrice=b.maxPrice===""||b.maxPrice==null?null:Number(b.maxPrice),minRating=b.minRating===""||b.minRating==null?null:Number(b.minRating),latitude=finiteCoord(b.latitude,90),longitude=finiteCoord(b.longitude,180),radiusKm=b.radiusKm==null?null:Number(b.radiusKm);if(name.length<2||!(["Todos",...Object.keys(categories)].includes(kind))||!(category==="Todas"||Object.values(categories).flat().includes(category))||!(city==="Todas las ciudades"||cities.includes(city))||!(condition==="todos"||condition==="nuevo"||condition==="usado")||minPrice!==null&&(!Number.isFinite(minPrice)||minPrice<0)||maxPrice!==null&&(!Number.isFinite(maxPrice)||maxPrice<0)||minPrice!==null&&maxPrice!==null&&minPrice>maxPrice||minRating!==null&&(!Number.isInteger(minRating)||minRating<1||minRating>5)||(latitude===null)!==(longitude===null)||radiusKm!==null&&(!Number.isInteger(radiusKm)||radiusKm<2||radiusKm>100))return NextResponse.json({error:"Revisa los filtros de la búsqueda"},{status:400});try{const db=getDb(),existing=await db.select({id:savedSearches.id}).from(savedSearches).where(eq(savedSearches.userId,uid));if(existing.length>=20)return NextResponse.json({error:"Puedes guardar hasta 20 búsquedas"},{status:400});const [row]=await db.insert(savedSearches).values({userId:uid,name,query,kind,category,city,minPrice,maxPrice,condition,minRating,latitude,longitude,radiusKm,createdAt:new Date().toISOString()}).returning({id:savedSearches.id});return NextResponse.json({id:row.id},{status:201})}catch(e){console.error("saved search add",e);return NextResponse.json({error:"No se pudo guardar la búsqueda"},{status:503})}}
