import { getUserId } from "../../../lib-auth";
import { NextRequest,NextResponse } from "next/server";
import { getDb } from "../../../db";
import { favorites,ads } from "../../../db/schema";
import { eq,and } from "drizzle-orm";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){const uid=await getUserId(req);if(!uid)return NextResponse.json({ids:[]});try{return NextResponse.json({ids:(await getDb().select({adId:favorites.adId}).from(favorites).where(eq(favorites.userId,uid))).map(x=>x.adId)})}catch(e){console.error("favorites get",e);return NextResponse.json({error:"Favoritos no disponibles"},{status:503})}}
export async function POST(req:NextRequest){const uid=await getUserId(req);if(!uid)return NextResponse.json({error:"Inicia sesión para guardar favoritos"},{status:401});const b=await req.json().catch(()=>({})) as Record<string,unknown>;const adId=Number(b.adId);if(!Number.isSafeInteger(adId))return NextResponse.json({error:"Anuncio inválido"},{status:400});try{const db=getDb(),ad=(await db.select({id:ads.id,hiddenAt:ads.hiddenAt}).from(ads).where(eq(ads.id,adId)).limit(1))[0];if(!ad||ad.hiddenAt)return NextResponse.json({error:"Anuncio no disponible"},{status:404});await db.insert(favorites).values({userId:uid,adId,createdAt:new Date().toISOString()}).onConflictDoNothing();return NextResponse.json({ok:true})}catch(e){console.error("favorite add",e);return NextResponse.json({error:"No se pudo guardar"},{status:503})}}
export async function DELETE(req:NextRequest){const uid=await getUserId(req);if(!uid)return NextResponse.json({error:"Inicia sesión"},{status:401});const adId=Number(new URL(req.url).searchParams.get("adId"));if(!Number.isSafeInteger(adId))return NextResponse.json({error:"Anuncio inválido"},{status:400});try{await getDb().delete(favorites).where(and(eq(favorites.userId,uid),eq(favorites.adId,adId)));return NextResponse.json({ok:true})}catch(e){console.error("favorite delete",e);return NextResponse.json({error:"No se pudo quitar"},{status:503})}}
