import { getSessionUser } from "../../../lib-auth";
import { NextRequest,NextResponse } from "next/server";
import { getDb } from "../../../db";
import { ads,conversations,reports,profiles } from "../../../db/schema";
import { isAdmin } from "../../../lib-admin";
import { eq,and,isNotNull,isNull,desc } from "drizzle-orm";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){if(!isAdmin((await getSessionUser(req))?.email||null))return NextResponse.json({error:"Acceso restringido"},{status:403});try{const db=getDb(),pending=await db.select().from(reports).where(eq(reports.status,"pendiente")).orderBy(desc(reports.id)).limit(100),requests=await db.select({userId:profiles.userId,displayName:profiles.displayName,city:profiles.city,whatsapp:profiles.whatsapp,verificationRequestedAt:profiles.verificationRequestedAt}).from(profiles).where(and(eq(profiles.accountType,"empresa"),isNotNull(profiles.verificationRequestedAt),isNull(profiles.verifiedAt))).limit(100);return NextResponse.json({reports:pending,requests})}catch(e){console.error("moderation get",e);return NextResponse.json({error:"Revisión no disponible"},{status:503})}}
export async function POST(req:NextRequest){if(!isAdmin((await getSessionUser(req))?.email||null))return NextResponse.json({error:"Acceso restringido"},{status:403});let b:Record<string,unknown>;try{b=await req.json()}catch{return NextResponse.json({error:"Datos inválidos"},{status:400})}const action=b.action,id=Number(b.id),db=getDb(),now=new Date().toISOString();try{
 if(action==="verify_company"){const userId=typeof b.userId==="string"?b.userId:"";if(!userId||b.checkedOfficialRecord!==true)return NextResponse.json({error:"Confirma primero la comprobación del registro oficial"},{status:400});const updated=await db.update(profiles).set({verifiedAt:now,verificationRequestedAt:null}).where(and(eq(profiles.userId,userId),eq(profiles.accountType,"empresa"),isNotNull(profiles.verificationRequestedAt))).returning({userId:profiles.userId});return updated.length?NextResponse.json({ok:true}):NextResponse.json({error:"Solicitud no encontrada"},{status:404})}
 if(action==="reject_company"){const userId=typeof b.userId==="string"?b.userId:"";await db.update(profiles).set({verificationRequestedAt:null}).where(eq(profiles.userId,userId));return NextResponse.json({ok:true})}
 if(!Number.isSafeInteger(id)||!(action==="dismiss"||action==="hide_ad"))return NextResponse.json({error:"Acción inválida"},{status:400});const report=(await db.select().from(reports).where(and(eq(reports.id,id),eq(reports.status,"pendiente"))).limit(1))[0];if(!report)return NextResponse.json({error:"Denuncia no encontrada"},{status:404});if(action==="hide_ad"){if(report.targetType!=="anuncio")return NextResponse.json({error:"Solo puedes ocultar anuncios"},{status:400});await db.update(ads).set({hiddenAt:now}).where(eq(ads.id,report.targetId))}await db.update(reports).set({status:action==="hide_ad"?"oculto":"descartado",resolvedAt:now}).where(eq(reports.id,id));return NextResponse.json({ok:true})
 }catch(e){console.error("moderation action",e);return NextResponse.json({error:"No se pudo completar la revisión"},{status:503})}}
