import { getSessionUser } from "../../../lib-auth";
import { NextRequest,NextResponse } from "next/server";
import { getDb } from "../../../db";
import { profiles,ads,reviews,photos } from "../../../db/schema";
import { eq,desc,inArray } from "drizzle-orm";
import { cities,cleanText,validPhone } from "../../../lib-market";
import { isAdmin } from "../../../lib-admin";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){const sessionUser=await getSessionUser(req),userId=sessionUser?.id;if(!userId)return NextResponse.json({signedIn:false});try{const db=getDb();const profile=(await db.select().from(profiles).where(eq(profiles.userId,userId)).limit(1))[0]||null;const ownAds=await db.select().from(ads).where(eq(ads.owner,userId)).orderBy(desc(ads.createdAt)).limit(100);const images=ownAds.length?await db.select().from(photos).where(inArray(photos.adId,ownAds.map(a=>a.id))):[];const ratings=await db.select().from(reviews).where(eq(reviews.subjectId,userId));return NextResponse.json({signedIn:true,isAdmin:isAdmin(sessionUser?.email||null),userId,email:sessionUser?.email||"",profile,ads:ownAds.map(a=>({...a,photos:images.filter(p=>p.adId===a.id).map(p=>`/api/photos/${p.id}`)})),ratings:{count:ratings.length,average:ratings.length?Math.round(ratings.reduce((a,r)=>a+r.stars,0)/ratings.length*10)/10:null,items:ratings.map(r=>({stars:r.stars,comment:r.comment,createdAt:r.createdAt}))}})}catch(e){console.error("me get",e);return NextResponse.json({error:"Perfil no disponible"},{status:503})}}
export async function PUT(req:NextRequest){const sessionUser=await getSessionUser(req),userId=sessionUser?.id;if(!userId)return NextResponse.json({error:"Inicia sesión."},{status:401});let body:Record<string,unknown>;try{body=await req.json()}catch{return NextResponse.json({error:"Datos inválidos"},{status:400})}const displayName=cleanText(body.displayName,60),accountType=cleanText(body.accountType),bio=cleanText(body.bio,500),city=cleanText(body.city),whatsapp=cleanText(body.whatsapp),showWhatsapp=body.showWhatsapp===true?1:0;if(displayName.length<2||!(["persona","empresa"].includes(accountType))||(city&&!cities.includes(city))||(whatsapp&&!validPhone(whatsapp))||(showWhatsapp&&!whatsapp))return NextResponse.json({error:"Revisa los datos del perfil."},{status:400});try{const db=getDb(),existing=(await db.select().from(profiles).where(eq(profiles.userId,userId)).limit(1))[0],changedIdentity=!!existing&&(existing.displayName!==displayName||existing.accountType!==accountType);const verifiedAt=changedIdentity||accountType!=="empresa"?null:existing?.verifiedAt||null,verificationRequestedAt=changedIdentity||accountType!=="empresa"?null:existing?.verificationRequestedAt||null,now=new Date().toISOString();await db.insert(profiles).values({userId,displayName,accountType,bio,city,whatsapp,showWhatsapp,verifiedAt,verificationRequestedAt,updatedAt:now,joinedAt:now}).onConflictDoUpdate({target:profiles.userId,set:{displayName,accountType,bio,city,whatsapp,showWhatsapp,verifiedAt,verificationRequestedAt,updatedAt:now}});return NextResponse.json({ok:true})}catch(e){console.error("me update",e);return NextResponse.json({error:"No se pudo guardar el perfil."},{status:503})}}
